name: stockalert_pro
description: AI-powered stock monitoring app
version: 1.0.0+1
publish_to: 'none'

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  http: ^1.1.0
  firebase_core: ^2.24.0
  firebase_messaging: ^14.7.6
  firebase_auth: ^4.15.0
  cloud_firestore: ^4.13.3
  shared_preferences: ^2.2.2
  flutter_local_notifications: ^16.2.0
  provider: ^6.1.1
  intl: ^0.18.1
  fl_chart: ^0.65.0
  cupertino_icons: ^1.0.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1

flutter:
  uses-material-design: true